//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS
    {
        public BUS()
        {
            this.ASIENTO = new HashSet<ASIENTO>();
            this.ITINERARIO = new HashSet<ITINERARIO>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdTipoBus { get; set; }
        public int Interno { get; set; }
        public string Placa { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<ASIENTO> ASIENTO { get; set; }
        public virtual TIPO_BUS TIPO_BUS { get; set; }
        public virtual ICollection<ITINERARIO> ITINERARIO { get; set; }
    }
}
