//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public CAJA()
        {
            this.CAJA_USUARIO = new HashSet<CAJA_USUARIO>();
        }
    
        public long Id { get; set; }
        public string NroCaja { get; set; }
    
        public virtual ICollection<CAJA_USUARIO> CAJA_USUARIO { get; set; }
    }
}
