//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.DETALLE_SOLICITUD_ASIENTO = new HashSet<DETALLE_SOLICITUD_ASIENTO>();
            this.SOLICITUD_PASAJE = new HashSet<SOLICITUD_PASAJE>();
            this.SOLICITUD_RESERVA = new HashSet<SOLICITUD_RESERVA>();
        }
    
        public long Id { get; set; }
        public Nullable<int> NIT { get; set; }
    
        public virtual JURIDICO JURIDICO { get; set; }
        public virtual NATURAL NATURAL { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_ASIENTO> DETALLE_SOLICITUD_ASIENTO { get; set; }
        public virtual ICollection<SOLICITUD_PASAJE> SOLICITUD_PASAJE { get; set; }
        public virtual ICollection<SOLICITUD_RESERVA> SOLICITUD_RESERVA { get; set; }
    }
}
