//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD_ASIENTO
    {
        public long IdSolicitudPasaje { get; set; }
        public long IdAsiento { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public Nullable<long> IdItinerario { get; set; }
    
        public virtual ASIENTO ASIENTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ITINERARIO ITINERARIO { get; set; }
        public virtual SOLICITUD_PASAJE SOLICITUD_PASAJE { get; set; }
    }
}
