//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSIFICACION
    {
        public DOSIFICACION()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public long Id { get; set; }
        public Nullable<int> NroTramite { get; set; }
        public Nullable<int> NroIncial { get; set; }
        public Nullable<int> NroFinal { get; set; }
        public string Llave { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
