//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.USUARIO = new HashSet<USUARIO>();
            this.SOLICITUD_PASAJE = new HashSet<SOLICITUD_PASAJE>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdCargo { get; set; }
        public int CI { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual ICollection<SOLICITUD_PASAJE> SOLICITUD_PASAJE { get; set; }
    }
}
