//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public HORARIO()
        {
            this.DETALLE_DEPARTAMENTO_HORARIO = new HashSet<DETALLE_DEPARTAMENTO_HORARIO>();
        }
    
        public long Id { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual ICollection<DETALLE_DEPARTAMENTO_HORARIO> DETALLE_DEPARTAMENTO_HORARIO { get; set; }
    }
}
