//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_PASAJE
    {
        public long IdAsiento { get; set; }
        public Nullable<int> NroAsiento { get; set; }
        public long IdCliente { get; set; }
        public Nullable<int> CI { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
