//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIO
    {
        public ITINERARIO()
        {
            this.DETALLE_SOLICITUD_ASIENTO = new HashSet<DETALLE_SOLICITUD_ASIENTO>();
            this.DETALLE_SOLICITUD_RESERVA = new HashSet<DETALLE_SOLICITUD_RESERVA>();
        }
    
        public long Id { get; set; }
        public long IdBus { get; set; }
        public long IdUsuario { get; set; }
        public long IdDepartamento { get; set; }
        public long IdHorario { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Precio { get; set; }
    
        public virtual BUS BUS { get; set; }
        public virtual DETALLE_DEPARTAMENTO_HORARIO DETALLE_DEPARTAMENTO_HORARIO { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_ASIENTO> DETALLE_SOLICITUD_ASIENTO { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_RESERVA> DETALLE_SOLICITUD_RESERVA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
