//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PASAJE
    {
        public SOLICITUD_PASAJE()
        {
            this.DETALLE_SOLICITUD_ASIENTO = new HashSet<DETALLE_SOLICITUD_ASIENTO>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public Nullable<long> IdEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_ASIENTO> DETALLE_SOLICITUD_ASIENTO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
