//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CAJA_USUARIO = new HashSet<CAJA_USUARIO>();
            this.ITINERARIO = new HashSet<ITINERARIO>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdEmpleado { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<CAJA_USUARIO> CAJA_USUARIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<ITINERARIO> ITINERARIO { get; set; }
    }
}
