//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BUSTIPO
    {
        public long Id { get; set; }
        public Nullable<long> IdTipoBus { get; set; }
        public int Interno { get; set; }
        public string Placa { get; set; }
        public int Estado { get; set; }
        public Nullable<int> NroColumnas { get; set; }
        public string Nombre { get; set; }
    }
}
