//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FACTURA
    {
        public long IdFactura { get; set; }
        public long IdSolicitud { get; set; }
        public long IdCliente { get; set; }
        public int Interno { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan Hora { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<int> NIT { get; set; }
        public string CodigoControl { get; set; }
        public byte[] QR { get; set; }
        public int NroAsiento { get; set; }
        public string Cliente { get; set; }
        public string Pasajero { get; set; }
    }
}
