//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INFORMACION_ITINERARIOS
    {
        public long IdItinerario { get; set; }
        public long IdHorario { get; set; }
        public long IdDepartamento { get; set; }
        public long IdUsuario { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Departamento { get; set; }
        public System.DateTime Fecha { get; set; }
        public long IdBus { get; set; }
        public string Detalle { get; set; }
        public string DetalleCompleto { get; set; }
    }
}
