//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Ventas.Pasaje.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ITINERARIO_BUS_ASIENTO
    {
        public long IdDepartamento { get; set; }
        public string Departamento { get; set; }
        public long IdItinerario { get; set; }
        public System.DateTime Fecha { get; set; }
        public long IdBus { get; set; }
        public int Interno { get; set; }
        public System.TimeSpan Hora { get; set; }
        public long IdAsiento { get; set; }
        public string Asiento { get; set; }
        public int NroAsiento { get; set; }
        public string TipoBus { get; set; }
        public Nullable<int> NroColumnas { get; set; }
        public decimal Precio { get; set; }
    }
}
